auto: true
server: true
exclude: README.md, .gitignore
permalink: none
baseurl: 
url: http://nodepdx.org
hashtag: '#nodepdx'
github_login: 'nodepdx'
github_repo: 'nodepdx.github.com'
github_lanaguage: 'JavaScript'
